version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt install -y ruby-full
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
  post_build:
    commands:
      - echo Entered the post_build phase...
artifacts:
  files:
    - '**/*'