version: 0.2

phases:
  build:
    commands:       
      - docker build -t $DOCKER_BUILD_NAME .
      - docker tag $DOCKER_BUILD_NAME  $AWS_PUSH/$DOCKER_BUILD_NAME  
  post_build:
    commands:
      - docker push $AWS_PUSH/$DOCKER_BUILD_NAME